fileVersion: 1
id: "2"
mappingDefinitions:
  ADP_COMBINED:
    database: LRS_PRODUCTION
    schema: ADP_COMBINED
  ADP_RAW:
    database: LRS_RAW
    schema: ADP_RAW
  ADP_WORKFORCE_NOW:
    database: LRS_RAW
    schema: ADP_WORKFORCE_NOW
  CUSTOMER_SERVICE_DATA_MODEL:
    database: LRS_PRODUCTION
    schema: CUSTOMER_SERVICE_DATA_MODEL
  FINANCIAL_DATA_MODEL:
    database: LRS_PRODUCTION
    schema: FINANCIAL_DATA_MODEL
  LOGGING_DATA:
    database: LRS_RAW
    schema: TRUX_LOGGING_RAW
  MASTER_DATA:
    database: LRS_RAW
    schema: MASTER_DATA
  MASTER_DATA_CLEAN:
    database: LRS_PRODUCTION
    schema: MASTER_DATA_CLEAN
  OPERATIONS_DATA_MODEL:
    database: LRS_PRODUCTION
    schema: OPERATIONS_DATA_MODEL
  SAGE_CDC_ACTDAT:
    database: LRS_CDC_PROD
    schema: SG_CDC_ACTDAT
  SAGE_CDC_BLDDAT:
    database: LRS_CDC_PROD
    schema: SG_CDC_BLDDAT
  SAGE_CDC_ECODAT:
    database: LRS_CDC_PROD
    schema: SG_CDC_ECODAT
  SAGE_CDC_EXCDAT:
    database: LRS_CDC_PROD
    schema: SG_CDC_EXCDAT
  SAGE_CDC_HOVDAT:
    database: LRS_CDC_PROD
    schema: SG_CDC_HOVDAT
  SAGE_CDC_HRTDAT:
    database: LRS_CDC_PROD
    schema: SG_CDC_HRTDAT
  SAGE_CDC_LAKDAT:
    database: LRS_CDC_PROD
    schema: SG_CDC_LAKDAT
  SAGE_CDC_LAKDIS:
    database: LRS_CDC_PROD
    schema: SG_CDC_LAKDIS
  SAGE_CDC_LAKPDA:
    database: LRS_CDC_PROD
    schema: SG_CDC_LAKPDA
  SAGE_CDC_LAKSDA:
    database: LRS_CDC_PROD
    schema: SG_CDC_LAKSDA
  SAGE_CDC_LECDAT:
    database: LRS_CDC_PROD
    schema: SG_CDC_LECDAT
  SAGE_CDC_LIADAT:
    database: LRS_CDC_PROD
    schema: SG_CDC_LIADAT
  SAGE_CDC_LINDAT:
    database: LRS_CDC_PROD
    schema: SG_CDC_LINDAT
  SAGE_CDC_LRSDCT:
    database: LRS_CDC_PROD
    schema: SG_CDC_LRSDCT
  SAGE_CDC_MANDAT:
    database: LRS_CDC_PROD
    schema: SG_CDC_MANDAT
  SAGE_CDC_RAMDAT:
    database: LRS_CDC_PROD
    schema: SG_CDC_RAMDAT
  SAGE_CDC_RECDAT:
    database: LRS_CDC_PROD
    schema: SG_CDC_RECDAT
  SAGE_COMBINED:
    database: LRS_PRODUCTION
    schema: SAGE_COMBINED_RAW
  SG_ACTDAT:
    database: LRS_RAW
    schema: SG_ACTDAT_DBO
  SG_BLDDAT:
    database: LRS_RAW
    schema: SG_BLDDAT_DBO
  SG_ECODAT:
    database: LRS_RAW
    schema: SG_ECODAT_DBO
  SG_EXCDAT:
    database: LRS_RAW
    schema: SG_EXCDAT_DBO
  SG_HOVDAT:
    database: LRS_RAW
    schema: SG_HOVDAT_DBO
  SG_HRTDAT:
    database: LRS_RAW
    schema: SG_HRTDAT_DBO
  SG_LAKDAT:
    database: LRS_RAW
    schema: SG_LAKDAT_DBO
  SG_LAKDIS:
    database: LRS_RAW
    schema: SG_LAKDIS_DBO
  SG_LAKPDA:
    database: LRS_RAW
    schema: SG_LAKPDA_DBO
  SG_LAKSDA:
    database: LRS_RAW
    schema: SG_LAKSDA_DBO
  SG_LECDAT:
    database: LRS_RAW
    schema: SG_LECDAT_DBO
  SG_LIADAT:
    database: LRS_RAW
    schema: SG_LIADAT_DBO
  SG_LINDAT:
    database: LRS_RAW
    schema: SG_LINDAT_DBO
  SG_LRSDCT:
    database: LRS_RAW
    schema: SG_LRSDCT_DBO
  SG_MANDAT:
    database: LRS_RAW
    schema: SG_MANDAT_DBO
  SG_RAMDAT:
    database: LRS_RAW
    schema: SG_RAMDAT_DBO
  SG_RECDAT:
    database: LRS_RAW
    schema: SG_RECDAT_DBO
  SOFTPAK_CLEAN:
    database: LRS_PRODUCTION
    schema: SOFTPAK_CLEAN
  SOFTPAK_RAW:
    database: LRS_RAW
    schema: SOFTPAK_RAW
  TOWER_COMBINED:
    database: LRS_PRODUCTION
    schema: TOWER_COMBINED_RAW
  TOWER_RAW:
    database: LRS_RAW
    schema: TOWER_RAW
  TRUXCOMBINED_RAW:
    database: LRS_PRODUCTION
    schema: TRUX_COMBINED_RAW
  TRUX_AL_COMP_RAW:
    database: LRS_RAW
    schema: TRX_AL_DBO
  TRUX_AM_COMP_RAW:
    database: LRS_RAW
    schema: TRX_AM_DBO
  TRUX_AS_COMP_RAW:
    database: LRS_RAW
    schema: TRX_AS_DBO
  TRUX_AT_COMP_RAW:
    database: LRS_RAW
    schema: TRX_AT_DBO
  TRUX_BC_COMP_RAW:
    database: LRS_RAW
    schema: TRX_BC_DBO
  TRUX_BH_COMP_RAW:
    database: LRS_RAW
    schema: TRX_BH_DBO
  TRUX_CD_COMP_RAW:
    database: LRS_RAW
    schema: TRX_CD_DBO
  TRUX_DC_COMP_RAW:
    database: LRS_RAW
    schema: TRX_DC_DBO
  TRUX_DF_COMP_RAW:
    database: LRS_RAW
    schema: TRX_DF_DBO
  TRUX_ES_COMP_RAW:
    database: LRS_RAW
    schema: TRX_ES_DBO
  TRUX_HA_COMP_RAW:
    database: LRS_RAW
    schema: TRX_HA_DBO
  TRUX_HR_COMP_RAW:
    database: LRS_RAW
    schema: TRX_HR_DBO
  TRUX_IC_COMP_RAW:
    database: LRS_RAW
    schema: TRX_IC_DBO
  TRUX_IP_COMP_RAW:
    database: LRS_RAW
    schema: TRX_IP_DBO
  TRUX_LR_COMP_RAW:
    database: LRS_RAW
    schema: TRX_LR_DBO
  TRUX_MD_COMP_RAW:
    database: LRS_RAW
    schema: TRX_MD_DBO
  TRUX_ME_COMP_RAW:
    database: LRS_RAW
    schema: TRX_ME_DBO
  TRUX_MF_COMP_RAW:
    database: LRS_RAW
    schema: TRX_MF_DBO
  TRUX_MH_COMP_RAW:
    database: LRS_RAW
    schema: TRX_MH_DBO
  TRUX_MM_COMP_RAW:
    database: LRS_RAW
    schema: TRX_MM_DBO
  TRUX_MN_COMP_RAW:
    database: LRS_RAW
    schema: TRX_MN_DBO
  TRUX_MO_COMP_RAW:
    database: LRS_RAW
    schema: TRX_MO_DBO
  TRUX_MP_COMP_RAW:
    database: LRS_RAW
    schema: TRX_MP_DBO
  TRUX_MW_COMP_RAW:
    database: LRS_RAW
    schema: TRX_MW_DBO
  TRUX_NI_COMP_RAW:
    database: LRS_RAW
    schema: TRX_NI_DBO
  TRUX_PS_COMP_RAW:
    database: LRS_RAW
    schema: TRX_PS_DBO
  TRUX_RD_COMP_RAW:
    database: LRS_RAW
    schema: TRX_RD_DBO
  TRUX_RT_COMP_RAW:
    database: LRS_RAW
    schema: TRX_RT_DBO
  TRUX_RW_COMP_RAW:
    database: LRS_RAW
    schema: TRX_RW_DBO
  TRUX_SH_COMP_RAW:
    database: LRS_RAW
    schema: TRX_SH_DBO
  TRUX_SW_COMP_RAW:
    database: LRS_RAW
    schema: TRX_SW_DBO
  TRUX_TP_COMP_RAW:
    database: LRS_RAW
    schema: TRX_TP_DBO
  TRUX_UA_COMP_RAW:
    database: LRS_RAW
    schema: TRX_UA_DBO
  TRUX_UB_COMP_RAW:
    database: LRS_RAW
    schema: TRX_UB_DBO
  TRUX_UC_COMP_RAW:
    database: LRS_RAW
    schema: TRX_UC_DBO
  TRUX_V9_COMP_RAW:
    database: LRS_RAW
    schema: TRX_V9_DBO
  TRUX_VA_COMP_RAW:
    database: LRS_RAW
    schema: TRX_VA_DBO
  TRUX_VB_COMP_RAW:
    database: LRS_RAW
    schema: TRX_VB_DBO
  TRUX_VC_COMP_RAW:
    database: LRS_RAW
    schema: TRX_VC_DBO
  TRUX_VE_COMP_RAW:
    database: LRS_RAW
    schema: TRX_VE_DBO
  TRUX_VI_COMP_RAW:
    database: LRS_RAW
    schema: TRX_VI_DBO
  TRUX_WA_COMP_RAW:
    database: LRS_RAW
    schema: TRX_WA_DBO
  TRUX_XI_COMP_RAW:
    database: LRS_RAW
    schema: TRX_XI_DBO
  TRX_CDC_AL:
    database: LRS_CDC_PROD
    schema: TRX_CDC_AL
  TRX_CDC_AM:
    database: LRS_CDC_PROD
    schema: TRX_CDC_AM
  TRX_CDC_AS:
    database: LRS_CDC_PROD
    schema: TRX_CDC_AS
  TRX_CDC_AT:
    database: LRS_CDC_PROD
    schema: TRX_CDC_AT
  TRX_CDC_BC:
    database: LRS_CDC_PROD
    schema: TRX_CDC_BC
  TRX_CDC_BH:
    database: LRS_CDC_PROD
    schema: TRX_CDC_BH
  TRX_CDC_CD:
    database: LRS_CDC_PROD
    schema: TRX_CDC_CD
  TRX_CDC_DC:
    database: LRS_CDC_PROD
    schema: TRX_CDC_DC
  TRX_CDC_DF:
    database: LRS_CDC_PROD
    schema: TRX_CDC_DF
  TRX_CDC_ES:
    database: LRS_CDC_PROD
    schema: TRX_CDC_ES
  TRX_CDC_HA:
    database: LRS_CDC_PROD
    schema: TRX_CDC_HA
  TRX_CDC_HR:
    database: LRS_CDC_PROD
    schema: TRX_CDC_HR
  TRX_CDC_IC:
    database: LRS_CDC_PROD
    schema: TRX_CDC_IC
  TRX_CDC_IP:
    database: LRS_CDC_PROD
    schema: TRX_CDC_IP
  TRX_CDC_LR:
    database: LRS_CDC_PROD
    schema: TRX_CDC_LR
  TRX_CDC_MD:
    database: LRS_CDC_PROD
    schema: TRX_CDC_MD
  TRX_CDC_ME:
    database: LRS_CDC_PROD
    schema: TRX_CDC_ME
  TRX_CDC_MF:
    database: LRS_CDC_PROD
    schema: TRX_CDC_MF
  TRX_CDC_MH:
    database: LRS_CDC_PROD
    schema: TRX_CDC_MH
  TRX_CDC_MM:
    database: LRS_CDC_PROD
    schema: TRX_CDC_MM
  TRX_CDC_MN:
    database: LRS_CDC_PROD
    schema: TRX_CDC_MN
  TRX_CDC_MO:
    database: LRS_CDC_PROD
    schema: TRX_CDC_MO
  TRX_CDC_MP:
    database: LRS_CDC_PROD
    schema: TRX_CDC_MP
  TRX_CDC_MW:
    database: LRS_CDC_PROD
    schema: TRX_CDC_MW
  TRX_CDC_NI:
    database: LRS_CDC_PROD
    schema: TRX_CDC_NI
  TRX_CDC_PS:
    database: LRS_CDC_PROD
    schema: TRX_CDC_PS
  TRX_CDC_RD:
    database: LRS_CDC_PROD
    schema: TRX_CDC_RD
  TRX_CDC_RT:
    database: LRS_CDC_PROD
    schema: TRX_CDC_RT
  TRX_CDC_RW:
    database: LRS_CDC_PROD
    schema: TRX_CDC_RW
  TRX_CDC_SH:
    database: LRS_CDC_PROD
    schema: TRX_CDC_SH
  TRX_CDC_SW:
    database: LRS_CDC_PROD
    schema: TRX_CDC_SW
  TRX_CDC_TP:
    database: LRS_CDC_PROD
    schema: TRX_CDC_TP
  TRX_CDC_UA:
    database: LRS_CDC_PROD
    schema: TRX_CDC_UA
  TRX_CDC_UB:
    database: LRS_CDC_PROD
    schema: TRX_CDC_UB
  TRX_CDC_UC:
    database: LRS_CDC_PROD
    schema: TRX_CDC_UC
  TRX_CDC_V9:
    database: LRS_CDC_PROD
    schema: TRX_CDC_V9
  TRX_CDC_VA:
    database: LRS_CDC_PROD
    schema: TRX_CDC_VA
  TRX_CDC_VB:
    database: LRS_CDC_PROD
    schema: TRX_CDC_VB
  TRX_CDC_VC:
    database: LRS_CDC_PROD
    schema: TRX_CDC_VC
  TRX_CDC_VE:
    database: LRS_CDC_PROD
    schema: TRX_CDC_VE
  TRX_CDC_VI:
    database: LRS_CDC_PROD
    schema: TRX_CDC_VI
  TRX_CDC_WA:
    database: LRS_CDC_PROD
    schema: TRX_CDC_WA
  TRX_CDC_XI:
    database: LRS_CDC_PROD
    schema: TRX_CDC_XI
  VENA_RAW:
    database: LRS_RAW
    schema: VENA_RAW
name: Production
type: Environment
