fileVersion: 1
id: 9425bb4a-b006-4eb4-ac29-d62b89055565
name: COMPOSE_VW_AMCS_EMPLOYEE_ID_UPDATE
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: ADP_LYRIQ
  metadata:
    columns:
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 1b98d850-6f7d-47da-ac3a-3a69f770518c
          stepCounter: 9425bb4a-b006-4eb4-ac29-d62b89055565
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: EMPLOYEE_ID
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 1cf8ea84-c995-41fb-afba-77dcb26c8b98
          stepCounter: 9425bb4a-b006-4eb4-ac29-d62b89055565
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: FIRST_NAME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 17df736c-bcc2-4c8e-bb5c-68843a583155
          stepCounter: 9425bb4a-b006-4eb4-ac29-d62b89055565
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: LAST_NAME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 7a698d68-a5a7-4b0a-ac3d-5f54e039527f
          stepCounter: 9425bb4a-b006-4eb4-ac29-d62b89055565
        config: {}
        dataType: DATE
        defaultValue: ""
        description: ""
        name: HIRE_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
  name: COMPOSE_VW_AMCS_EMPLOYEE_ID_UPDATE
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
