fileVersion: 1
id: 168c981f-a7da-4794-a4ed-188c34b07c73
name: SURCHARGE_PARAMETER_CONFIGURATION_CUSTOMER_MASTER
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
    truncateBefore: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TRUXCOMBINED_RAW
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 965394e3-9839-450b-a263-d3885d404fb2
          stepCounter: 168c981f-a7da-4794-a4ed-188c34b07c73
        config: {}
        dataType: VARCHAR(100)
        description: ""
        name: SP01_NAME
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c3f9fc67-7aec-4a50-86d6-43878c0fb715
                stepCounter: b4afd444-f750-4026-9d7f-709d8fde9979
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 56309654-b009-411b-8ae2-543ede62a47e
          stepCounter: 168c981f-a7da-4794-a4ed-188c34b07c73
        config: {}
        dataType: VARCHAR(2)
        description: ""
        name: SP01_UOM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a44d6f1a-3e4c-4328-bad3-568029d34000
                stepCounter: b4afd444-f750-4026-9d7f-709d8fde9979
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f8105724-72e4-4942-8a73-7d4bf0f8e281
          stepCounter: 168c981f-a7da-4794-a4ed-188c34b07c73
        config: {}
        dataType: BOOLEAN
        description: ""
        name: SP01_DEFA
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: fcf3aec0-821c-40c7-9652-21ba4ffa13bd
                stepCounter: b4afd444-f750-4026-9d7f-709d8fde9979
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: de1e7cfd-e403-4d89-87f0-516a0b8f0066
          stepCounter: 168c981f-a7da-4794-a4ed-188c34b07c73
        config: {}
        dataType: BOOLEAN
        description: ""
        name: SP01_ZERO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c8a85fe5-47ca-49a2-93e1-638b3011a0ed
                stepCounter: b4afd444-f750-4026-9d7f-709d8fde9979
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 29c0bb2b-e56e-4cad-bc8f-5ce48fa43056
          stepCounter: 168c981f-a7da-4794-a4ed-188c34b07c73
        config: {}
        dataType: NUMBER(11,2)
        description: ""
        name: SP01_MINA
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: eaf655e9-9057-4489-b4a3-011d33191091
                stepCounter: b4afd444-f750-4026-9d7f-709d8fde9979
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d3d50b4d-16e5-4d8b-a165-1d2340274f8b
          stepCounter: 168c981f-a7da-4794-a4ed-188c34b07c73
        config: {}
        dataType: BOOLEAN
        description: ""
        name: SP01_MULTIPLY
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 8f0e90af-0ac6-4803-af9f-a95b53974e95
                stepCounter: b4afd444-f750-4026-9d7f-709d8fde9979
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 954d0c32-1f05-4f81-a0f2-c732c77dbcb7
          stepCounter: 168c981f-a7da-4794-a4ed-188c34b07c73
        config: {}
        dataType: VARCHAR(2)
        description: ""
        name: SP01_CODE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c5822033-2146-42d0-8132-52cea0bc5f62
                stepCounter: b4afd444-f750-4026-9d7f-709d8fde9979
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: abca8641-b550-447f-9c2c-02e03a86bb91
          stepCounter: 168c981f-a7da-4794-a4ed-188c34b07c73
        config: {}
        dataType: NUMBER(38,0)
        description: ""
        name: SP01_ID
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e9e4c196-82c1-488f-a22d-4ad70a8b835b
                stepCounter: b4afd444-f750-4026-9d7f-709d8fde9979
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 98ec76eb-7620-447c-a319-d7488a2e8345
          stepCounter: 168c981f-a7da-4794-a4ed-188c34b07c73
        config: {}
        dataType: VARCHAR(2)
        description: ""
        name: SP01_MATUOM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a52f56aa-eafe-45aa-b1e2-684b6ec04697
                stepCounter: b4afd444-f750-4026-9d7f-709d8fde9979
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1d3a4788-6e03-4261-a97c-00b6bc402638
          stepCounter: 168c981f-a7da-4794-a4ed-188c34b07c73
        config: {}
        dataType: VARCHAR(1)
        description: ""
        name: SP01_SORD
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 2bc4e40c-398a-447b-a8eb-f3371c337a69
                stepCounter: b4afd444-f750-4026-9d7f-709d8fde9979
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 56fd4340-45bf-4f9b-95eb-e18f56ba78b3
          stepCounter: 168c981f-a7da-4794-a4ed-188c34b07c73
        config: {}
        dataType: BOOLEAN
        description: ""
        name: SP01_MULTDB
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 0b735030-a028-4d21-a02b-0f77dfac4291
                stepCounter: b4afd444-f750-4026-9d7f-709d8fde9979
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e85e5b82-4459-4cdb-8d32-4c3d91e14f35
          stepCounter: 168c981f-a7da-4794-a4ed-188c34b07c73
        config: {}
        dataType: BOOLEAN
        description: ""
        name: SP01_NONEG
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 3a29ef4e-af20-46c3-b449-6baa89d6a818
                stepCounter: b4afd444-f750-4026-9d7f-709d8fde9979
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 92ffb252-d1cb-4ee4-b217-131d009c5300
          stepCounter: 168c981f-a7da-4794-a4ed-188c34b07c73
        config: {}
        dataType: NUMBER(18,2)
        description: ""
        name: SP01_PERCENT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 4a974d3a-c51a-4c20-b602-158bc53d82b2
                stepCounter: b4afd444-f750-4026-9d7f-709d8fde9979
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5289940f-0141-4b4a-a251-91460257e705
          stepCounter: 168c981f-a7da-4794-a4ed-188c34b07c73
        config: {}
        dataType: NUMBER(11,2)
        description: ""
        name: SP01_MAXA
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: bcf2ef40-f9b6-4549-bc41-fbd0a2b88380
                stepCounter: b4afd444-f750-4026-9d7f-709d8fde9979
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0da7d2bb-f67d-4d34-a728-5cd91f3cc242
          stepCounter: 168c981f-a7da-4794-a4ed-188c34b07c73
        config: {}
        dataType: BOOLEAN
        description: ""
        name: SP01_PAPER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: fbdb874c-74da-4e55-8819-71ab3a13df35
                stepCounter: b4afd444-f750-4026-9d7f-709d8fde9979
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9b899c8f-af3a-444b-8a1e-6d5c376a97c3
          stepCounter: 168c981f-a7da-4794-a4ed-188c34b07c73
        config: {}
        dataType: NUMBER(18,2)
        description: ""
        name: SP01_FLAT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 2484f92a-f643-4d6f-a62b-3802d01eb887
                stepCounter: b4afd444-f750-4026-9d7f-709d8fde9979
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ca2620d8-9466-4d87-a9fa-53bcb32a9cd1
          stepCounter: 168c981f-a7da-4794-a4ed-188c34b07c73
        config: {}
        dataType: BOOLEAN
        description: ""
        name: SP01_ACTIVE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 419cbce3-780b-460e-86ad-4c329e10cb02
                stepCounter: b4afd444-f750-4026-9d7f-709d8fde9979
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cd14e20d-4f98-4396-92a2-09c222e0e8b1
          stepCounter: 168c981f-a7da-4794-a4ed-188c34b07c73
        config: {}
        dataType: BOOLEAN
        description: ""
        name: _FIVETRAN_DELETED
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 0fee0ddb-5961-489a-91ed-0572b0e7a2a1
                stepCounter: b4afd444-f750-4026-9d7f-709d8fde9979
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e28d24a2-5ae2-4ba7-85dd-66a21f0579d4
          stepCounter: 168c981f-a7da-4794-a4ed-188c34b07c73
        config: {}
        dataType: TIMESTAMP_TZ(9)
        description: ""
        name: _FIVETRAN_SYNCED
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 99cd2779-ec6b-4fc5-9c77-fdac9df7cd7b
                stepCounter: b4afd444-f750-4026-9d7f-709d8fde9979
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d2ba49ec-18f6-4ca1-ad8b-af8df6e3bd7c
          stepCounter: 168c981f-a7da-4794-a4ed-188c34b07c73
        config: {}
        dataType: VARCHAR
        description: ""
        name: SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 74830d50-e02f-4ddc-bc04-ffc06e2649ad
                stepCounter: b4afd444-f750-4026-9d7f-709d8fde9979
            transform: ""
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          STG_SP01_COMBINED: b4afd444-f750-4026-9d7f-709d8fde9979
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TRUXCOMBINED_RAW
            nodeName: STG_SP01_COMBINED
        join:
          joinCondition: |-
            FROM {{ ref('TRUXCOMBINED_RAW', 'STG_SP01_COMBINED') }} "STG_SP01_COMBINED"

            WHERE SP01_ACTIVE = 1
        name: SURCHARGE_PARAMETER_CONFIGURATION_CUSTOMER_MASTER
        noLinkRefs: []
  name: SURCHARGE_PARAMETER_CONFIGURATION_CUSTOMER_MASTER
  overrideSQL: false
  schema: ""
  sqlType: Stage
  type: sql
  version: 1
type: Node
